spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tsinjo_prod
    username: postgres
    password: prodSecret
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
